# render.yaml
services:
  - type: web
    name: nutrition-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server:app"  # âœ… not app:app
    plan: free
    envVars:
      - key: PORT
        value: 10000

